/* eslint-disable prettier/prettier */
export const data = [
  {
    name: 'Iphone 15',
    description: 'The best smartphone in the world',
    price: 199.99,
    stock: 12,
    category: 'smartphone',
    imgUrl: 'text',
  },
  {
    name: 'Samsung Galaxy S23',
    description: 'The best smartphone in the world',
    price: 150.0,
    stock: 12,
    category: 'smartphone',
    imgUrl: 'text',
  },
  {
    name: 'Motorola Edge 40',
    description: 'The best smartphone in the world',
    price: 179.89,
    stock: 12,
    category: 'smartphone',
    imgUrl: 'text',
  },
  {
    name: 'Samsung Odyssey G9',
    description: 'The best monitor in the world',
    price: 299.99,
    stock: 12,
    category: 'monitor',
    imgUrl: 'text',
  },
  {
    name: 'LG UltraGear',
    description: 'The best monitor in the world',
    price: 199.99,
    stock: 12,
    category: 'monitor',
    imgUrl: 'text',
  },
  {
    name: 'Acer Predator',
    description: 'The best monitor in the world',
    price: 150.0,
    stock: 12,
    category: 'monitor',
    imgUrl: 'text',
  },
  {
    name: 'Razer BlackWidow V3',
    description: 'The best keyboard in the world',
    price: 99.99,
    stock: 12,
    category: 'keyboard',
    imgUrl: 'text',
  },
  {
    name: 'Corsair K70',
    description: 'The best keyboard in the world',
    price: 79.99,
    stock: 12,
    category: 'keyboard',
    imgUrl: 'text',
  },
  {
    name: 'Logitech G Pro',
    description: 'The best keyboard in the world',
    price: 59.99,
    stock: 12,
    category: 'keyboard',
    imgUrl: 'text',
  },
  {
    name: 'Razer Viper',
    description: 'The best mouse in the world',
    price: 49.99,
    stock: 12,
    category: 'mouse',
    imgUrl: 'text',
  },
  {
    name: 'Logitech G502 Pro',
    description: 'The best mouse in the world',
    price: 39.99,
    stock: 12,
    category: 'mouse',
    imgUrl: 'text',
  },
  {
    name: 'SteelSeries Rival 3',
    description: 'The best mouse in the world',
    price: 29.99,
    stock: 12,
    category: 'mouse',
    imgUrl: 'text',
  },
  // {
  //   name: 'Lentes con protección de luz azul',
  //   description: 'Cuidan tu vista de las pantallas',
  //   price: 19.99,
  //   stock: 10,
  //   category: 'glasses',
  //   imgUrl: 'text',
  // },
  // {
  //   name: 'Audífonos con protección para oídos',
  //   description: 'Cuidan tus oídos del ruido',
  //   price: 12.99,
  //   stock: 10,
  //   category: 'headphones',
  //   imgUrl: 'text',
  // },
];
