/* eslint-disable prettier/prettier */
export const data = [
  {
    name: 'Iphone 15',
    description: 'The best smartphone in the world',
    price: 199.99,
    stock: 1,
    category: 'smartphone',
    imgUrl: '',
  },
  {
    name: 'Samsung Galaxy S23',
    description: 'The best smartphone in the world',
    price: 150.0,
    stock: 12,
    category: 'smartphone',
  },
  {
    name: 'Motorola Edge 40',
    description: 'The best smartphone in the world',
    price: 179.89,
    stock: 12,
    category: 'smartphone',
    imgUrl: 'text',
  },
  {
    name: 'Samsung Odyssey G9',
    description: 'The best monitor in the world',
    price: 299.99,
    stock: 12,
    category: 'monitor',
    imgUrl: 'text',
  },
  {
    name: 'LG UltraGear',
    description: 'The best monitor in the world',
    price: 199.99,
    stock: 12,
    category: 'monitor',
    imgUrl: 'text',
  },
  {
    name: 'Acer Predator',
    description: 'The best monitor in the world',
    price: 150.0,
    stock: 12,
    category: 'monitor',
    imgUrl: 'text',
  },
  {
    name: 'Razer BlackWidow V3',
    description: 'The best keyboard in the world',
    price: 99.99,
    stock: 12,
    category: 'keyboard',
    imgUrl: 'text',
  },
  {
    name: 'Corsair K70',
    description: 'The best keyboard in the world',
    price: 79.99,
    stock: 12,
    category: 'keyboard',
    imgUrl: 'text',
  },
  {
    name: 'Logitech G Pro',
    description: 'The best keyboard in the world',
    price: 59.99,
    stock: 12,
    category: 'keyboard',
    imgUrl: 'text',
  },
  {
    name: 'Razer Viper',
    description: 'The best mouse in the world',
    price: 49.99,
    stock: 12,
    category: 'mouse',
    imgUrl: 'text',
  },
  {
    name: 'Logitech G502 Pro',
    description: 'The best mouse in the world',
    price: 39.99,
    stock: 12,
    category: 'mouse',
    imgUrl: 'text',
  },
  {
    name: 'SteelSeries Rival 3',
    description: 'The best mouse in the world',
    price: 29.99,
    stock: 12,
    category: 'mouse',
    imgUrl: 'text',
  },
  // {
  //   name: "Blue Light Protection Glasses",
  //   description: "Protect your eyes from screen exposure",
  //   price: 19.99,
  //   stock: 10,
  //   category: "glasses",
  //   imgUrl: "text",
  // },
  // {
  //   name: "Hearing Protection Headphones",
  //   description: "Protect your ears from noise",
  //   price: 12.99,
  //   stock: 10,
  //   category: "headphones",
  //   imgUrl: "text",
  // },
];
